language: ruby
rvm:
- 2.0.0
bundler_args: --without doc guard --jobs 7
script: bundle exec rake build
deploy:
  provider: rubygems
  api_key:
    secure: j4qKRcVgSpULZXlSyGSt5WmHTCazXmH1uNNcfpUioIMOZkceh7CWspMps3FWSPIbINqLoSfzK4hJbUcnoqSZ79ho8NBbcNvqTIJXxFoYbhTgTlUwdNovgto4WmqwEYDSWp+ShryLqLkRY6WGFFUu2ve4eRum1akQcaxkQC1vjcKsQXUDFCY8qW6unsFQivV3YMX+baTHcOpB/YyEqwkHq5N6173U7eM0Rmu5F39PIKovb/wBLYomuV7vDH7kGvxernVguUNC0azgLe9j1lTQT1bkmn78pCwb9PYeW8xkkTWW0DSZf5n9TSG1jhECGUkmeNJbMBpFioApvYfEoyKq58vPPJ5eyjz5rvOshfwIefzOgdS6RoHMfWzA1StzPj3iQwnhow70vhU4vZJ3HI8pTyCv2szhItdBL6Z4Hc90KrXKX6HaBuRHw2wv48+tvoKU3hnguswrYer7nSOSfTKMxMHTNoevlieRNX/3Suh7/8laV1eobYRv7yUSkGpFdeT+8FqlSBJVG/A6fyct/DqOhMLV48y8Rc2pqDTdVJ638LAwdcUhvvqYe04i5Zxr7Qa0Wi89bHLRhR0R3o5pvgVAJt3wjVKKHz0kuN1cbP60B4d/Xmp8lQRL0MADAVfaiSJvI/vDMCt48/qBzRe4IQBMwI4iMCwDZ56DTyXKaGO08x8=
  gem: kitchen-vmm
  on:
    tags: true
    repo: jarig/kitchen-vmm
    all_branches: true
